# Generated by Django 2.2.3 on 2019-07-31 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=15)),
                ('lname', models.CharField(blank=True, max_length=15)),
                ('emailid', models.EmailField(max_length=50)),
                ('address', models.TextField(blank=True, max_length=100, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(max_length=200)),
                ('entityid', models.IntegerField(max_length=10)),
                ('type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=15)),
                ('lname', models.CharField(blank=True, max_length=15)),
                ('emailid', models.EmailField(max_length=50)),
                ('address', models.TextField(blank=True, max_length=100, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_no', models.IntegerField(max_length=10)),
                ('entityid', models.IntegerField(max_length=10)),
                ('type', models.CharField(max_length=15)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=15, null=True)),
                ('lname', models.CharField(blank=True, max_length=15, null=True)),
                ('emailid', models.EmailField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True, max_length=100, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
