# Generated by Django 2.2.3 on 2019-07-31 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
